### ISSUE TITLE
Why enumeration, not structure?

### ISSUE THREAD

**Issue by CoderYLZhang** [dreymonde/Time#3]
Time your code:

    public enum Second : TimeUnit {
    
        public static var toTimeIntervalRatio: Double {
            return 1
        }
    }
Why enumeration, not structure?

    public struct Second : TimeUnit {
    
        public static var toTimeIntervalRatio: Double {
            return 1
        }
    }

Is it better to enumerate than structure in here?
Why?

**Comment by dreymonde** [comment]
Thanks for your question! The reason is really simple:
By design, you cannot create instances of `Second`, you only can create instances of `Interval<Second>`. In Swift, `enum` without cases is the best way to create a type which _cannot be created_. If `Second` was a `struct`, one could accidentally write:

```swift
let second = Second()
```

Which wouldn’t make any sense and would be very confusing for the coder. But since `Second` is an `enum`, it results in a compile-time error:

```swift
let second = Second()
error: 'Second' cannot be constructed because it has no accessible initializers
```

**Comment by CoderYLZhang** [comment]
Thanks
